### ISSUE TITLE
Quantizing to 8-bit dtype for faster inference

### ISSUE THREAD

**Issue by akasharidas** [42Shawn/PTQ4DM#1]
I ran the `quant_model` function on a diffusion model, but I see that the resulting quantized model still has weights stored in `float`. There is no reduction in model size on disk. How do I convert them to `int8` to realize performance gains during inference? Or am I misunderstanding the purpose of this paper?

**Comment by 42Shawn** [comment]
This is the difference between ''fake'' quantization and ''real'' quantization. Please read the survey paper.
