### ISSUE TITLE
running script for CIFAR

### ISSUE THREAD

**Issue by kriskrisliu** [42Shawn/PTQ4DM#5]
Great job on this!
As the Imagenet model may cause an OOM error on my device, could you please provide the running script for CIFAR? 
Thank you.

**Comment by bcBest** [comment]
I got OOM too. And I'm curious about how to solve this on the imagenet dataset by mutiple GPUs.

**Comment by iszry** [comment]
I avoid OOM by reducing `--calib_num_samples`.

**Comment by tqch** [comment]
> I avoid OOM by reducing `--calib_num_samples`.

Adding an option of `calib_batch_size` will be better than reducing the size of the calibration set IMO.

**Comment by yuzheyao22** [comment]
I can not 

> Great job on this! As the Imagenet model may cause an OOM error on my device, could you please provide the running script for CIFAR? Thank you.

Same problem. It seems to be not easy to reproduce the paper's result on CIFAR10 with the script provided by improved-diffusion from OpenAI..
