### ISSUE TITLE
Generating calibration dataset 

### ISSUE THREAD

**Issue by tojiboyevf** [42Shawn/PTQ4DM#9]
Thanks for your work!
Could you please explain me the difference of between generating the calibration dataset of Image samples and Training-mimic? How do you generate the calibration dataset at time step t in Image samples case?

**Comment by hahnyuan** [comment]
Here are the key differences between generating the calibration dataset using Image samples versus Training-mimic:
﻿
## Calibration with Image samples:
﻿- Uses raw images as input for the calibration

## Calibration with Noise Samples:
- Uses Gaussian noise as input for calibration

## Calibration with Training-mimic samples:
- Uses a raw image to generate x_t by running the forward diffusion process starting from real images (x0) up to some time step t
- use x_t for calibration﻿
- This aims to mimic samples from the training distribution

**Comment by tojiboyevf** [comment]
Thank you for your response!
But in the paper you indicated equation 4 (diffusion process) in Training-mimic scheme. That's why I was confused.

**Comment by hahnyuan** [comment]
Sorry for my misunderstanding of your question. I checked the question and paper again and modify my yesterday's response.
